name: app_kit
description: "a useful app base kit."
version: 0.0.1
homepage: https://www.yfmingo.cn/
publish_to: 'none'  # 这行是关键！

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hud:
    path: /Users/mingo/allRepos/all_kit/hud
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus.git
#  flutter_pickers: ^2.1.9
  flutter_pickers:
    git:
      url: https://github.com/quewen08/flutter_pickers.git
      ref: 3168c16d5157dbaab3ba01aa273b98f531dc1263
  dio_log:
    path: /Users/mingo/allRepos/all_kit/dio_log/
#  dio_log:
#    git:
#      url: https://github.com/yfming93/dio_log.git
#      ref: 08d4515146d8d185dbf24b714bcffa5439779e19

  dio: 5.9.0
#  dio_log: ^5.3.0+3
  get: 4.7.3
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  permission_handler: 12.0.1
  connectivity_plus: 7.0.0
  camera: 0.11.3
  flutter_easyloading: ^3.0.5
  flutter_inappwebview: ^6.1.5 # flutter_inappwebview: 6.0.0-beta.23 #  ios out ipa error
  html: ^0.15.6
  url_launcher: 6.3.2
  package_info_plus: 9.0.0
  common_utils: ^2.1.0
  time: 2.1.6
  photo_view: ^0.15.0
  image_gallery_saver_plus: ^4.0.1
#  image_pickers: 2.0.6
  image_picker: 1.2.1
  cached_network_image: ^3.4.1 #不支持web
  device_info_plus: 12.3.0
  auto_size_text: ^3.0.0
  path_provider: ^2.1.5
  flutter_local_notifications: 19.5.0 #安装申请通知权限
  qr_code_dart_scan: 0.11.5
  card_swiper: ^3.0.1
  visibility_detector: ^0.4.0+2 #视图是否可见
  searchfield: 1.4.0
  flutter_tabbar_lite: ^0.0.6
  pro_image_editor: 11.14.1
  file_picker: 10.3.7
  shimmer: ^3.0.0
  table_calendar: ^3.2.0
  easy_refresh: ^3.4.0
  simple_animations: 5.2.0
  flutter_image_compress: ^2.4.0

#dependency_overrides:
#  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.10.4
  assets_scanner_plus: ^3.2.0 #dart run build_runner build

flutter:
  uses-material-design: true
  assets:
    - lib/ast/
    - lib/ast/images/
    - lib/ast/images/ic_copy.png


  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
